<a href="https://colab.research.google.com/github/zzzer0-wav/Analysis_Cafe_Sales/blob/main/EDA_cafe_sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Analysis Cafe Sales
Cafe Sales - Dirty Data for Cleaning Training

Overview

The Dirty Cafe Sales dataset contains 10,000 rows of synthetic data representing sales transactions in a cafe. This dataset is intentionally "dirty," with missing values, inconsistent data, and errors introduced to provide a realistic scenario for data cleaning and exploratory data analysis (EDA). It can be used to practice cleaning techniques, data wrangling, and feature engineering.
File Information

    File Name: dirty_cafe_sales.csv
    Number of Rows: 10,000
    Number of Columns: 8

| Column Name | Description |
| --- | --- |
| Transaction ID | A unique identifier for each transaction. Always present and unique. |
| Item | The name of the item purchased. May contain missing or invalid values (e.g., "ERROR"). |
| Quantity | The quantity of the item purchased. May contain missing or invalid values. |
| Price Per Unit | The price of a single unit of the item. May contain missing or invalid values. |
| Total Spent | The total amount spent on the transaction. Calculated as Quantity * Price Per Unit. |
| Payment Method | The method of payment used. May contain missing or invalid values (e.g., None, "UNKNOWN"). |
| Location | The location where the transaction occurred. May contain missing or invalid values. |
| Transaction Date | The date of the transaction. May contain missing or incorrect values. |

In [4]:
!pip install numpy pandas matplotlib

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Loading the dataset

In [7]:
url = 'https://raw.githubusercontent.com/zzzer0-wav/Analysis_Cafe_Sales/refs/heads/main/data/dirty_cafe_sales.csv'

In [8]:
df_origin = pd.read_csv(url)

In [10]:
df_origin.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [11]:
df = df_origin.copy()

### Initial diagnosis

In [13]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [17]:
print('Date types (raw):\n')
df.dtypes

Date types (raw):

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

Problem:

Numeric columns (Quantity, Price Per Unit, Total Spent)

Date columns (Transaction Date)

In [24]:
print('Missing values:\n')
missing = df.isna().sum()
missing_pct = (missing / len(df) * 100)
missing_report = pd.DataFrame({
    'count': missing,
    '%': missing_pct
})

missing_report[missing_report['count']>0]

Missing values:

                  count      %
Item                333   3.33
Quantity            138   1.38
Price Per Unit      179   1.79
Total Spent         173   1.73
Payment Method     2579  25.79
Location           3265  32.65
Transaction Date    159   1.59

In [28]:
print('Unique values:\n')

print('--- Item ---\n')
display(df['Item'].value_counts(dropna=False))

print('--- Payment method ---\n')
display(df['Payment Method'].value_counts(dropna=False))

print('--- Location ---\n')
display(df['Location'].value_counts(dropna=False))

Unique values:

--- Item ---

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64

--- Payment method ---

Payment Method
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

--- Location ---

Location
NaN         3265
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [33]:
print("Fing lines with 'ERROR' or 'UNKNOWN'\n")
display(df.isin(['ERROR', 'UNKNOWN']).any())
mask_error = df.isin(['ERROR', 'UNKNOWN']).any(axis=1).sum()
print(f"Lines with 'ERROR' or 'UNKNOWN': {mask_error.sum()}")

Fing lines with 'ERROR' or 'UNKNOWN'

Transaction ID      False
Item                 True
Quantity             True
Price Per Unit       True
Total Spent          True
Payment Method       True
Location             True
Transaction Date     True
dtype: bool

Lines with 'ERROR' or 'UNKNOWN': 2845

Замість TRUE/FALSE записати кількість ERROR & UNKNOWN у стовпчиках